name: Test CI

on: [push, pull_request, pull_request_review]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: false
          persist-credentials: false

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Format
        run: deno fmt --check --config deno.json

      - name: Lint
        run: deno lint --config deno.json

      - name: Test
        run: deno test --allow-all

